### ISSUE TITLE
formating the temp list clears everything

### ISSUE THREAD

**Issue by gaddi** [VR51/host-flash#1]
This version does not work for me. Only credits are added to Hosts. The bug is in the formatting or cleaning stage of the temp host file. Version 1.21 (Junior) works as expected.

**Comment by VR51** [comment]
Thanks Gaddi. Will take a look at it.

**Comment by VR51** [comment]
Time passes too quickly. I've rebuilt Host Flash. New features. Bugs fixed. New menu system. Hope you like it @gaddi.
